### ISSUE TITLE
Labor Market in Finland

### ISSUE THREAD

**Issue by pedpess** [staltz/ama#13]
Hi Andre,

Firstly, thanks for having this space to share some of ur knowledge and point of view about stuff not always related to coding. 

I'm soon graduating in Information Systems and lately I have been working as Android Developer in Sao Paulo. In few months I will be moving to Finland for a new chapter of my life and sincerely I'm a bit apprehensive about what the labor market there would expect from me as a recent graduated student in the near future. 

Could you share a bit of ur story of what obstacles did you have to fight against since you have moved there?

Thank u very much! =)

**Comment by staltz** [comment]
Hi Pedro!

Overall I didn't have to fight against anything here. I adapted very well to the finnish culture and quite quickly. Maybe I would have trouble adapting to the Brazilian work culture. 

But there're a few things to keep in mind in Finland when working:

- When meeting new people, shake hands, look at each others eyes, and say your name. Just that. It's simple but it's an important ritual. And remember their names, because it's embarrassing if you ask again.
- Always be punctual. Always. If the meeting is at 15:00, arrive 14:57. Always.
- if someone asks you what you think, just say exactly what you think and keep it rather short.
- Be prepared to be independent and to think for yourself. If you need to ask for help, ask only to people whose *job is to help you*. Don't expect your work colleague to help you in every single small issue. They might get annoyed.
- Small talk is about the weather and usually does not last long. If it's not summer, complain about the weather a bit, and then go straight to the point in the meeting. If it's summer, complain about wishing to be outside, then go straight to the point.
