### ISSUE TITLE
In Cycle.js do you interpret Observables as Events only? Or Behaviors, too?

### ISSUE THREAD

**Issue by DavidMihola** [staltz/ama#16]
_(This is less of a technical question and more about the way you think about the problem you are solving. It is motivated by my own Android app, in which I am using my own AHISBRIOHO* cycle.js and in which I am having trouble deciding whether to favor conceptual purity or a pragmatic approach.)_

When I am modeling a problem with RxJava, I tend/prefer to think of Observables as some state varying over time, i. e. a Behavior. However, most sources are certainly Events (clicks, network responses, etc.) and sinks can be either, depending on whether I am using some "virtual DOM" library like Anvil or whether I have to produce imperative output, e. g. by controlling ExoPlayer through method calls. (In some cases all it takes a renaming to go from Event to Behavior, e. g. `HIDE`/`SHOW` vs. `GONE`/`VISIBLE`).

**So, when writing stuff in cycle.js, do you keep a strict separation of Events and States or do you interpret the Observables in whatever way best suits the situation.**

Thanks for any thoughts!

`*` Ad-Hoc, Informally-Specified, Bug-Ridden, Implementation Of Half Of.

**Comment by staltz** [comment]
I usually interpret Observables as Events only. Even when I'm modelling a time-varying value, I *implement* that idea as Events, where I deliver one initial Event for each newly arrived subscriber (in the case of a shared Observable). That's how I interpret a BehaviorSubject for instance.

That's my rationale explained in this talk: https://www.youtube.com/watch?v=BfZpr0USIi4 where I say that we can work only with Events, we don't need to think in terms of State (i.e. Behaviors). The reason is that classic Behaviors are continuous in time (like functions in the real numbers) and need a more careful treatment to guarantee accuracy when transformed with formulas. In Rx, when we repeat the latest event, this is just one naive way to *emulate* Behaviors through Events. So, to stay honest, I assume that I only have Events as tool to work with.

That said, I find the idea of [Push-Pull FRP](http://conal.net/papers/push-pull-frp/push-pull-frp.pdf) beautiful. In a nutshell, it's about reacting to Events and sampling Behaviors. I have yet to see a nice implementation of this for JavaScript, but options like https://github.com/briancavalier/arrow and https://github.com/phadej/menrva come close.

PS: sorry for taking so long.

**Comment by DavidMihola** [comment]
Thank you very much for the reply!

I will definitely check out your talk - I hadn't come across that one before - and also have a look at the Push-Pull FRP stuff you mentioned.
