### ISSUE TITLE
How many hours did you work (including OS) per week and how do you get it? 

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#2]

**Comment by staltz** [comment]
I used to have a full-time job. During that time, I would come home from work and start doing open-source, for instance Cycle.js. I don't watch TV, I don't like movies, sometimes I play some games, I rarely read some books, I'm not so good at contacting friends for going out, and I don't like parties. So it turns out I had a lot of time. Probably during 2015, I spent about 30 hours per month doing open-source. Nowadays I have a part-time job, which frees me to do open-source much more. To be honest I haven't even measured how many hours landing for open-source lately.
