### ISSUE TITLE
How to think majorly in terms of streams

### ISSUE THREAD

**Issue by fvnilo** [staltz/ama#24]
Hi Andre,

**Context**

Reactivity.. streams.. pushing effects to the edge of our apps, these concepts really talk to me. My gut feeling is that this is how I should be building web apps.

I tried Cycle.js last year and really liked it but I didn't feel I was very much productive. Also, last year there weren't many routing library (that I liked), but I saw that there is one on cycle-community.

**My question is:** 

My question has two parts..

What habits should I develop to think of an app majorly in terms of streams and is there a line to draw?

The second part of my question is in reference to your [talk at GOTO 2016 in November](https://www.youtube.com/watch?v=Tkjg179M-Nc). You said that Cycle.js wasn't good for call-and-response mechanisms, for example HTTP requests. My real question here is probably more about: is it reasonable to think of streams everywhere or did you sometime have to tell yourself "Okay whoa.. this isn't working".

Thank you!

**Comment by staltz** [comment]
Hi Ny, thanks for the questions.

Sometime ago the idea of streams and dataflow clicked with me and has felt much more natural than typical imperative UI programming. I guess that once that click happens in your brain, it's hard to go back.

I feel like it's like asking Germans is it hard for them to speak in german all the time. They will promptly answer to you that it feels absolutely natural. With languages, you can learn how to speak them, but at some maturity level, you will start *thinking* in them.

To help getting to that level, I recommend drawing diagrams (at least that's how my brain works, with visualizations). Check this https://github.com/cyclejs/cyclejs/tree/master/devtool and this http://staltz.com/how-to-debug-rxjs-code.html

It may even help to draw such diagrams before writing any code. And then, when writing code, updating the diagram. This is possible because the concepts of streams and dataflow diagrams match perfectly.

> The second part of my question is in reference to your talk at GOTO 2016 in November. You said that Cycle.js wasn't good for call-and-response mechanisms, for example HTTP requests. My real question here is probably more about: is it reasonable to think of streams everywhere or did you sometime have to tell yourself "Okay whoa.. this isn't working".

In another question in this AMA someone asked about that and I answered in detail. https://github.com/staltz/ama/issues/22#issuecomment-288274072
The short answer is 'doing chained HTTP requests in the frontend is an indication that something is probably wrong or missing in the backend'.

**Comment by fvnilo** [comment]
Thank you @staltz.

I believe your advice will help me get a better grasp of all these concepts.

Come visit us in Canada someday ;-)
