### ISSUE TITLE
Question about Reactive Programming 

### ISSUE THREAD

**Issue by joshhornby** [staltz/ama#25]
Hi Andre,

We have recently built a phone system using [Twilio](www.twilio.com), our tech stack was React, Redux and Redux Saga. The app it's self is a mixture of API calls to a backend and websockets pushing data into our apps via middleware, which then dispatch redux actions. Depending on the data coming in from the websocket, drives what the UI looks like. 

We didn't really follow design patterns when building the app, and in turn I feel it could of turned out better. (Lots of if statements and case statements in multiple components, strange errors due to state not being in sync etc) Looking at the reactive programming concepts maybe this would be a good fit for our app (Our app basically reacting to the new data passed to it from websockets, and then calling HTTP endpoints based on the users actions)? Would you agree?

Do you have any good ideas of refactoring from a big ball of Redux code to nice clean streams?

**Comment by staltz** [comment]
Hi @joshhornby, thanks for asking.

I would totally use http://redux-observable.js.org/ in this case, since it fits in Redux well and therefore makes it easier to migrate/refactor code, piece by piece. You could even deploy your app to production where part of the async effects are managed by redux-saga and parts by redux-observable, eventually moving most of it to redux-observable. The docs have plenty of examples how to solve similar use cases to what you described.

If I had started from scratch, though, I would have chosen Cycle.js and xstream, since that is what I'm used to anyway, and it has good declarative composition of not only virtual DOM, but also any type of effect (imagine declaratively composing **websocket components**, not just VDOM components).

**Comment by marcusradell** [comment]
Since I'm doing react and most.js as a hobby, I just want to add an overview of mapping from redux parts to observable streams. You can stop reading here since I was not asked to answer.

Action creators: Action streams can be implemented with Subject.

Reducers: Map action streams to reducer function callback streams `(stateData) => (actionData + stateData)`. Hardest step, but it's an established design pattern.

Store: implement with scan operator. Part of the reducer solution.

CombineReducers: combine operator. But note that if each action creator is a single stream, you combine upwards without switch/case. And you don't really need to combine from the start.

Some do a single store with a single Subject and then filter downwards. I don't get why, and never did it like that myself.

Connect: See: https://github.com/marcusnielsen/reactive-tournament/blob/development/src/utils/connect-observer.js
This removes the need to combine state. But it comes at a cost of handing over the lifecycle to React and keeping streams isolated instead of merging/combining upwards.
You can also combine upwards and skip connect, but that would give some extra data passing complexity instead.

Server API: Do like redux-observable does with epics, except you can skip the filtering on action types.

Global slices (shared data) can be injected via a context/provider. Let them be stateful but viewless and then inject them to view components where ever you want to display the shared data.

Warning: This is not meant to be a recommendation. I wanted to give some reference point if you were thinking about state management with streams that replace redux-react. Above gives a somewhat overview of a possible roadmap. I hope I didn't step over any boundaries here by writing this!

**Comment by troch** [comment]
It feels a bit like I'm hijacking the AMA, but to share what I know: we've open-sourced a library recently called Refract, which makes reactive programming fully possible in React (it resembles cyclejs and cyclejs/react) : [https://github.com/fanduel-oss/refract](https://github.com/fanduel-oss/refract). It is many things at once, and can replace redux-observable entirely with the benefits of colocating logic to components (better code splitting / isolation results), and it supports xstream / most / RxJS / Callbag out of the box (choose the right package, no adapter needed).

**Comment by marcusradell** [comment]
We really need one React + Observable tool to win the battle! There's so many solutions out there now.

I guess it's just too easy (or more likely; fun) to start rolling your own.
