### ISSUE TITLE
What are your thoughts about Blockstack?

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#29]
Hi Andre,

Considering your recent efforts around scuttlebut and decentralized networks, I would like to hear your thoughts about [Blockstack](https://blockstack.org/) and the ideas presented in [this talk](https://pusher.com/sessions/meetup/js-monthly-london/decentralizing-the-internet-with-serverless-single-page-javascript-apps) from Larry Salibra (one of the members), specially around blockchains scalability and how to make all this decentralization a real thing for day-to-day.

Thanks.

**Comment by staltz** [comment]
Hi @geovanisouza92!

In short, Blockstack is a good thing. There are plenty of decentralized platforms out there, and it's good to have diversity so we experiment and find the most reliable platforms. I have some reservations on the fact that it is Bitcoin-backed because nowadays it can be hard to host a Bitcoin node on your computer, you have to download a lot of GB for the blockchain. Also, because it's tied to this global thing, there shouldn't be forks. So this requires users to be connected to the global internet, which can be hard to achieve in situations where the government is in control or ISPs do something in between. With net neutrality being threatened nowadays, you don't want to depend on your ISP granting you access to Blockstack or not. So ideally, a mesh network is better because it doesn't depend on anything remote. In SSB, "dns" or naming is subjective because it's impossible to resolve naming conflicts globally. They call this subjectivity, and instead of fighting it, we can try to [embrace it](https://www.youtube.com/watch?v=P5K18XssVBg) and see what kinds of apps can we build that support subjectivity. Isn't it great that you can name yourself "Geovani" without globally reserving that name only to you? That's independence. 

So overall, I'm not trying to put SSB versus Blockstack. Blockstack is great, we should explore it. We just need to be aware of the tradeoffs and sensitivity to governments and ISPs.

Thanks for asking
