### ISSUE TITLE
What language/library would you have liked to create?

### ISSUE THREAD

**Issue by midudev** [staltz/ama#3]
If you had to choose one language or library of the past or present development, what one would you choose? Cycle.js is not eligible. 😋

**Comment by Frikki** [comment]
Motorcyclejs

**Comment by TylorS** [comment]
Motorcycle.js is eligible? :smiley:

**Comment by staltz** [comment]
I really wish I would have invented Elm.

In other words I really admire and subscribe to Evan's ideas for functional programming. Functional programming is actually very easy. It's actually one of the easiest types of programming there is. It's just unfortunate that it gets mixed up with category theory and exotic and diverse syntax in Haskell. Evan got that, and he decided to write a functional programming language where it becomes obvious that functional programming is easy, not scary at all, and make it mainstream.

I still remember meeting Evan as one of the nicest experiences. He's definitely number one to me as the smartest and most empathetic programmers I've met. Here's a picture of us in MLOC.js 2015:

![11235289_499302526894802_935580600637616528_o](https://cloud.githubusercontent.com/assets/90512/20340897/8a37a266-abec-11e6-85c3-25528fff4417.jpg)

So I really wish I would have invented Elm. And that's also why I am sometimes critical of Elm: because it's so dear to my heart that I don't want it to go to the wrong direction. Now on one hand, I trust what Evan chooses, but on the other hand if I would have invented it myself, I wouldn't have taken the same choices in all the details.

Here are some things that I really wish wouldn't have happened in Elm:
- Signals only first-order
- Signals removed
- Update function returns tuple of Model and Cmd (it mixes concerns)
- Type classes not yet supported
- Comma-first convention (I prefer something like Coffeescript or Python)

So sometimes I toyed with the idea of making a language that is a sister to Elm. And then it hits me how much work that would require. And then my respect for Evan just grows.
