### ISSUE TITLE
Visual programming with NoFlo + babel-parser + babel-generator for Cycle.js

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#31]
André, I was thinking about how we could achieve a visual programming language with high *debuggability* and pretty visualization of events/signals flow, and came across https://noflojs.org/. I haven't tried (yet) to build some kind of integration with Cycle.js, but I think that this is possible, and maybe, could be integrated with a babel-parser to read existing code and babel-generator to keep source code in sync with NoFlo graphs.

Maybe this could contribute to cyclejs/cyclejs#579 and an idea that I registered on [cyclejs-community/cyclejs-community#12](https://github.com/cyclejs-community/cyclejs-community/issues/12#issuecomment-254385538).

What do you think about this?

**Comment by staltz** [comment]
Hi Geovani. :)

I have seen NoFlo before and I think it's a cool project. Maybe that path from NoFlo to babel to Cycle.js could work in some cases, but I'm not convinced it would work well always, because NoFlo's graph structure is not made for Cycle's dataflow graph, and there would be complicated parts like: how to render a collection of items, how to render higher order operators, etc. Nick Johnstone has a vision called [Bonsai editor](https://github.com/Widdershin/bonsai-editor) which is like NoFlo, but built from scratch specifically for Cycle.js, and I think we can bring that together with the DevTool. It's more work, but when it's built specifically for Cycle.js, it should work like expected, with less bugs.
