### ISSUE TITLE
Have you ever felt discouraged?

### ISSUE THREAD

**Issue by djyde** [staltz/ama#35]
Have you ever felt discouraged when doing opensource? 

Like if someone says "Oh Cycle.js is good, but everyone use React/Vue and why should I use Cycle." Will you feel discouraged?

I do opensource too, but few people use them. I always feel discouraged because it makes me feel what I did is not useful. 

How do you think of it?

**Comment by staltz** [comment]
Hi @djyde, this is a very good question.

I certainly do feel discouraged, sometimes. But it usually doesn't come from random people saying things about my libraries, it usually comes from close people, co-workers, friends, those are the people whose opinions matter most. They don't say *discouraging* comments about my projects, but I pay attention to what they *don't* say or do. It's usually the silence, the indifference, the passivity, that hurts most. I do and build stuff because I *believe* in something, for instance I believe that what I'm doing is useful and helps the world. It's scary to think that no one else might think the same, maybe I'm alone in this? Disagreements with close friends on (e.g.) altruism and free open source are able to weaken my motivation and make me sad.

What has helped me has been a simple guideline. *Ask yourself: in 10 years from now, will you be proud of having done this?* If the answer is yes, then do it no matter if you are completely alone in it. For instance, one of these old projects which I am very happy to have done was recording a [progressive album all by myself](https://soundcloud.com/andrestaltz/sets/o-vazio-tem-um-nome). To me, this was more valuable than many of my open source projects, but the album is little known, got little attention, basically no one cares about it. But I don't regret it one bit. Do things that your future self will be proud, is my motto for the time being.

Finally, back to the topic close friends, I once had a startup, and things started going bad, so we decided to pivot the startup to a different market. I wasn't sure what to do, and it was a close friend of mine who talked me out of doing it. Technically, he "discouraged" me from doing it, but I'm very thankful now for that, because it would have been one of those things my future self would not have been proud of doing.

Hope this encourages you too
