### ISSUE TITLE
What makes functional programming so viable for problem modeling?

### ISSUE THREAD

**Issue by newswim** [staltz/ama#4]
Thanks!

**Comment by staltz** [comment]
Functional programming is about purity. But I like to look at it as being about honesty.

When you see a function signature like `function render(age: number, name: string): VNode`, it is being honest to you about what it will accomplish in the implementation. It will take a number as an age, a string as a name and will return a VNode. 

In strict functional programming, if this function also does a console log or any other type of effect, then it must also tell that in its signature. This is why sometimes you see `IO` in the signature of some functions in Haskell: `add :: [String] -> IO ()`. The signature is a contract, and any implementation must fulfill this contract with honesty. In languages without the strict types, you can sometimes cheat by casting the type to another. So then it turns out that you could actually return number when the function should have returned a string. This is dishonesty.

So functional programming becomes more reliable for problem modeling because you can be sure that each part is being honest with its responsibility. 

On the other hand immutability is very central to functional programming. This is also a good property for problem modeling because you don't lose data. If you want to "modify" some data, you only create a new version of it. This helps you later on if you want to analyze some system, you have complete data for it. This is what enables time traveling debugging in systems like Elm or Redux.

Hope that answers it.

**Comment by uzantnomo** [comment]
@staltz there are popular functional languages without static typing or immutability (e.g. Clojure, Erlang, OCaml), what can you say about functional programming in these languages or in JavaScript?
