### ISSUE TITLE
Do you think it's wrong to sell software?

### ISSUE THREAD

**Issue by hossameldeen** [staltz/ama#43]
... and a question that must be asked with it: Do you think copyright is wrong?

Secretly, I wish for a debate, but this question isn't written with the intention of one; I'm just curious about your opinion. But if you do welcome a debate here, I'd be more than willing :-) (I'm not that hopeful, though).

**Comment by staltz** [comment]
Very interesting question, thanks for asking. I'm okay if you want to debate it, as opposed to just being answered once, but I can't guarantee I have the time to answer.

I wouldn't use the word "wrong", I don't think it applies that well, it's like saying "do you think the color green is wrong?", but I do find several problems with selling software and with copyright.

Let me start by answering that I think selling software should be legal, I don't think it is "wrong", but copyright is *unfitting* or *incompatible* with our mode of production in the internet era. My idea is that sales classify as *voluntary exchange*, and hence is a natural human activity. For instance, it would be fair and natural for one person to exchange a USB drive containing software for another commodity like a sandwich for instance. That's natural exchange. Replace the sandwich with currency, and it's sales. Do it in large scale, and it's a software business.

That said, as you acknowledge, usually software sales and copyright go hand in hand, because the latter protects the former from copies. I'll explain why I think copyright is unfitting, but to clarify what I imagine as an ideal world: it would allow software sales, but the pricing and scale of software sales would be nothing near the capitalistic scale today.

When you look at the history of Copyright, you'll see that it was an initiative by the state and the church (around Europe) to control and regulate the use of the printing press machines which were allowing people to spread information at an unprecedented scale that actually started threatening the control of the state. So it was not originally meant to defend authors, quite the contrary, it was meant to *control* authors, but over time, more powerful authors throughout the industrial revolution and peaking with Disney in the 20th century, were able to successfully weaponize Copyright laws for their protection.

But if you consider *copying* as a human act, it's hard to think of it as wrong. First of all, because humans are memetic machines. Since early age, an infant is copying behaviors from other humans. And in adulthood, most inventions are simply remixes (see [Everything is a Remix](https://www.everythingisaremix.info/watch-the-series/)).

It can be sometimes *unfair* when used in a market, for instance someone sells an article of mine, but it's not actively *hurting* me. What if someone would sell an article of mine in secret? If I don't know about it, I can't even sue them. I'm just missing an opportunity for also selling it, but no one is actively and directly harming me. It's just unfair, but is unfairness always illegal? It's funny that capitalism is usually completely compatible with "unfairness" through competition, but when it comes to copyright, then unfairness is weaponized to protect incumbents.

And when it comes to copying in the internet era, copying is one of the most basic operations a computer must do. The difference between computers copying and humans copying is that computers have perfect recall, while humans don't. For instance, if I tell the story of a movie, verbally, am I *copying* the movie? Quite often, no. But when computers tell the story of a movie, they are able to do that without flaw, they have perfect memory. Supposing humans would be very good at remembering (some people are able to memorize thousands of digits of the number Pi), I could memorize all the binary bits in an MP4 file, essentially copying and storing it in my brain. Is that illegal? It starts to become absurd, and unfitting with how we operate nowadays.

When you consider the natural instinctive copying behavior of humans, and the instant efficiency of copying in computers, then copying should be the most natural activity in the internet era, **and in practice it already is**, but we are slowed down by outdated laws that were weaponized to defend either the state or the incumbent big companies, not the people.

**Comment by hossameldeen** [comment]
A well-written reply, thanks for answering! No problem at all; understood :)

> the pricing and scale of software sales would be nothing near the capitalistic scale today.

Not a debate, but what is the pricing and scale of software sales today and what's wrong about it? If anything, I feel like we need more software to be sold, like what some famous IDE manufacturer does.

I've been writing this comment for more than an hour and I reached the opinion that I shouldn't use your space for debate. Perhaps I should debate your points in a blog post one day :-)

Thank you for for such an unassuming character!
