### ISSUE TITLE
Why isn't "callbags" written in typescript?

### ISSUE THREAD

**Issue by tusharmath** [staltz/ama#45]
It seems like most of the spec assumes the functions to be highly polymorphic even then i think it could easily be modelled using typescript.

There is a nice blog by @staltz about "why all js libraries should be authored in typescript" :D
https://staltz.com/all-js-libraries-should-be-authored-in-typescript.html

**Comment by staltz** [comment]
@tusharmath I love this question, because it's the tip of an interesting iceberg.

The answer is that Callbags is 100% written in TypeScript. Go to the main repo and you'll find that the only real code is a .d.ts file

But also, the only Callbag utilities I have built are callbag-basics (and other utils), and those are written in JavaScript.

The point here is that Callbags in total are an ecosystem of libraries, not one library. Libraries can (and perhaps should!) be written in a safer language, such as TypeScript, but if they are written in JS (which is totally valid, TS should not be a strict requirement), then things should continue to work correctly. This is because Callbags a lot more about the *interoperability between libraries*, not about *libraries themselves*.

The reason I authored many callbag libraries in JS is that I coded the first libraries on my phone in the airplane, and JS with raw node.js was easier than setting up TS configuration. But it could have as well been written in TS and that would not have altered the properties and benefits of Callbags, which are, again, mostly about the  interoperability.

**Comment by tusharmath** [comment]
As a POC I implemented a typescript based version for interval.

```ts
// tslint:disable


// Machinery
type Msg<T, V> = {type: T; value: V}
type Start<T> = Msg<0, T>
type Data<T> = Msg<1, T>
type End = Msg<2, void>
type InferMsgType<M> = M extends Msg<infer T, any> ? T : unknown
type InferMsgValue<M> = M extends Msg<any, infer V> ? V : unknown
type MsgCB<M extends Msg<any, any>> = (
  msg: Msg<InferMsgType<M>, InferMsgValue<M>>
) => void

// Helper functions
const data = <T>(t: T): Data<T> => ({type: 1, value: t})
const start = <T>(t: T): Start<T> => ({type: 0, value: t})
const end = (): End => ({type: 2, value: undefined})


// Typings for interval
type IntervalMsg = Start<MsgCB<Data<number> | Start<MsgCB<End>>>>

const interval = (period: number) => (msg: IntervalMsg) => {
  const sink = msg.value
  // I can get rid of this check because of typescript now :)
  if (msg.type === 0) { 
    let i = 0
    const id = setInterval(() => sink(data(i++)), period)

    sink(
      start(t => {
        if (t.type === 2) clearInterval(id)
      })
    )
  }
}
```
