### ISSUE TITLE
What's your overall opinion about crypto?

### ISSUE THREAD

**Issue by geovanisouza92** [staltz/ama#46]
- What kinds of problems it can resolve?
- Do you think that blockchain is more valuable than coins?
- Do you think that cryptocurrencies will replace fiat ("real") money?
- What steps do you think would be needed to transition from the current financial/commercial structure to a freedom-focussed one where crypto plays a fundamental role?

---

Thank you :smiley:

**Comment by staltz** [comment]
Took me a while to answer this, sorry @geovanisouza92 :)

My overall opinion on cryptocurrencies is mild and neutral. I think on one hand they are really revolutionary, and they are a big deal, but on the other hand I think there's a lot of unsolved problems. I'll describe both the positive side and the negative side.

The internet was a huge shift for humanity, probably as big the industrial revolution, and there must eventually be an internet-native currency, that works as an automated information system, not as a mountain of legal agreements. This would have positive effects for the economy (specially to the speed of transnational transactions, or to the possibility of microtransactions), positive effects for freedom, and it overall just makes sense, because financial transactions are very simple numerical operations, and it's weird that there isn't an internet-native currency. Also, as humanity becomes more global (i.e. nations become less relevant), we need to detach our dependency from USD (or any nation-state emitted currency), since that's an obvious single point of corruption and asymmetric privilege for USA. All this is to say that we need *some kind of internet-native currency*.

Bitcoin got close to being that. I was quite enthusiastic about Bitcoin in 2013, but not so much in 2018. I think Bitcoin made significant progress to *get the science closer* to achieving the internet-native currency (which is blockchain, proof-of-work, a p2p distributed ledger, and the use of cryptography), but Bitcoin is not yet the internet-native currency. Bitcoin does not scale well, because full nodes need to store the entire chain, and because proof-of-work gets more expensive to the environment (in energy consumption) the more we use it. It's disappointing that among all these cryptocurrency alternatives, we have a lot of esoteric use cases, and even a generic cryptocurrency (smart contracts, Ethereum as a world computer), but we still don't have a cryptocurrency that does just basic currency in a proper and scalable way. (Disclaimer: I don't research the cryptocurrency community that much to know all the alternatives, maybe someone solved this by now, not sure.) 

It's surprisingly hard to design an internet money system, just basic numerical money, with these properties: decentralized, peer-to-peer, permissionless, solves double spending problem, scalable to replace Visa, fast, global. So the right way to see it is that cryptocurrencies are a *research field*, but because they intersect with the financial world, there is a lot of hype and a lot of people trying to be the first major player, so it seems the research field is not yet matured but the industry around it is already mature and ready.

Finally, as I said in a [recent blog post](https://staltz.com/the-year-tech-giants-peaked-2018-a-retrospective.html), it may be that Bitcoin and other popular projects won't die even if we acknowledge their problems, simply because they are permissionless and open systems:

> Cryptocurrencies will have a good 2019. Most likely not an exponential kind of growth, maybe just linear or super-linear growth. While many have considered cryptocurrencies defeated after the bubble burst in late 2017, cryptocurrencies behave financially very differently than startups, growth companies, or commodities. These are open source and permissionless databases, which mean they don’t die easily. Growth companies have budget runways, commodities are subject to specific kinds of supply and demand. But open source and open data do not die, not until everyone has lost interest. Cryptocurrencies most likely have many winters, and experience the hype cycle multiple times, each plateau of productivity blending quickly with the next peak of inflated expectations.

**Comment by geovanisouza92** [comment]
Nevermind the delay, Thank you!
