### ISSUE TITLE
How do you see the future of visual coding tools?

### ISSUE THREAD

**Issue by carlbarrdahl** [staltz/ama#5]
Do you think we will move towards a more visual way of coding? And if so how do you think these tools would look and behave?

**Comment by staltz** [comment]
It's challenging.

Visual programming is not a new topic, it's been around longer than most of us have been alive. I won't attempt to explain why visual programming hasn't succeeded in the past, because I don't know the facts too well. I didn't study that history.

But there is one thing I noticed that may change our assumptions that enable or disable visual programming. Our programming models used to be dominantly imperative, dominantly for transformational systems. I talk thoroughly about transformation systems in this talk: https://youtu.be/Tkjg179M-Nc?t=867. In the past, flowcharts and UML diagrams were heavily used for describing transformational systems. Some advanced programs were even able to transform UML diagrams to code and vice-versa. That was their notion of visual programming _for that type of (imperative, OOP, transformational) programming_.

We are seeing a shift (albeit gradual and shy) towards functional programming and other paradigms that change our assumptions. Now we need to ask ourselves: what diagrams and visualizations make sense for this type of programming? For reactive programs, usually diagrams related to flow programming make a lot of sense for these new paradigms. Flow-based programming is probably older than functional programming, so now that functional programming has risen, we have the opportunity to attempt flow-based programming on top of functional programming. One such awesome attempt is Luna: http://www.luna-lang.org/.

Luna takes the right approach of being **both** a textual and visual programming language. It maintains the duality of text and diagram. Systems that attempted to be only visual programming have failed for diverse reasons. I think code is still often more accurate, more malleable (text editors [vim, emacs] are fantastic in this regard) and to some extent, very humane. Mankind has for a very long time relied on text for communication of ideas.

That said, flow-based programming or similar diagrams face the challenge of "higher-order something" (higher-order functions, higher-order streams, higher-order actors, etc). How do you visualize higher-order stuff? A static flow graph is often the best situation, but in many situations, to solve a problem, you need to go higher order. And I think how to visualize this stuff is still an unsolved problem.

So, it's challenging. I think the near future will be visual coding as a guide for textual coding. Things like Chrome DevTools with visualizations, or text editor minimaps, etc. These have more immediate potential of succeeding than a full-blown visual programming environment. Some concepts and processes are still a bit too abstract for visualization, yet text captures it well enough. I think the future is a careful balance and mix of visual and textual programming. Projects like Luna, [Cycle.js DevTool](https://github.com/cyclejs/cyclejs/tree/master/devtool), [Choo Graph Viz](https://github.com/forresto/choo-graph-viz), [React Monocle](https://github.com/team-gryff/react-monocle) are going in the right direction.
